### ISSUE TITLE
Telemetry events are no longer sent after setting a disable "DNSOverHTTPS" Enterprise Policy and restarting the browser

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/doh-rollout#94] opened 2019-09-20 12:29 UTC
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 71.0a1, Build ID 20190918215055
- Firefox Dev Edition 70.0b7, Build ID 20190916074538
- Firefox unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.6-signed-testing.xpi add-on is installed.
- A disable "DNSOverHTTPS" policy is set.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Restart the browser and navigate to "about:telemetry".
4. Observe the "Events" section.

[Expected result]:
- A "disable_doh" telemetry event is displayed after a restart.

[Actual result]:
- No telemetry events are displayed after a restart.

[Notes]:
- The "enable_doh" telemetry event is not sent after changing the policy to enable "DNSOverHTTPS" if it was previously disabled.
- This issue is only reproducible when setting up a policy using a policies.json file and not the Local Group Policy Editor on Windows.
- I have attached a screen recording of the issue:
![restart_ping](https://user-images.githubusercontent.com/40393891/65326983-674d5780-dbbb-11e9-8b7c-c0fa3800f6b2.gif)

**Comment by nhi-nguyen** [comment] 2019-09-20 18:38
@maxxcrawford we should run the enterprise policy heuristics on browser start as well, for reason @Softvision-PatriciuPop mentioned above.

**Comment by nhi-nguyen** [comment] 2019-09-20 18:40
@Softvision-PatriciuPop when browser restarts, if there has been nothing changed to the policy since the last event, there will be no telemetry events. This is by design.

**Comment by maxxcrawford** [comment] 2019-09-23 14:33
Closing this for now. Let me know if we should leave it open!

**Comment by Softvision-PatriciuPop** [comment] 2019-09-23 15:43
I wanted a 2nd opinion on this issue because I didn't want to mess up things with this somehow, so I've reached out to Mike Kaply, the engineer who works on Enterprise Policies. According to him, using policies.json files is supported and a widespread method of setting policies, which means that there is a high risk for the users to encounter this issue once the rollout is live.
There shouldn't be any differences between policies set using the json file and the Local Group Policy Editor as both use the same code path for setting preferences.

I have retested this using the latest add-on (0.0.7) and switching from a disable DoH policy to a enable DoH policy does not generate a telemetry event.

Do you think we should reconsider this and try to find a fix for it?

**Comment by maxxcrawford** [comment] 2019-09-23 15:47
@nhi-nguyen Thoughts?

**Comment by nhi-nguyen** [comment] 2019-09-23 19:38
The initial design only does enterprise policy check on network change. Thinking about it more, I think we should do it on startup as well, for the case mentioned here.

@maxxcrawford we should fix this.

**Comment by maxxcrawford** [comment] 2019-09-24 15:48
I'm going to test to see if this exists in https://github.com/mozilla/doh-rollout/releases/tag/0.0.8

**Comment by maxxcrawford** [comment] 2019-09-24 22:37
In regards to this, policies are only checked on browser start (with changes requiring a browser restart). I tested adding policies and they are respected. 

I think we can close this issue. Thoughts?  @nhi-nguyen @Softvision-PatriciuPop

**Comment by nhi-nguyen** [comment] 2019-09-24 22:49
Agree that browser restart is required.

However, I tested this scenario on unbranded 69 and there seems to be a bug there:
Steps:
* deploy an enterprise policy with DoH disable
```javascript
{
  "policies": {
    "DNSOverHTTPS": {
      "Enabled":  false
    }
  }
}
```
* install addon
* check that DoH is disabled, telemetry event sent (worked as expected)
* stop browser
* update `policies.json` to enable DoH (set `"Enabled": true`)
* restart browser
* check that DoH is enable, telemetry event sent (This didn't happen, no event was sent)

**Comment by maxxcrawford** [comment] 2019-09-25 21:36
@nhi-nguyen To confirm, restart browser means to completely close the application. On the restart, where the telemetry event SHOULD happen, but doesn't - what is the `network.trr.mode`?

**Comment by nhi-nguyen** [comment] 2019-09-25 22:28
@maxxcrawford yes, I closed Firefox completely and reopened it. On restart, `network.trr.mode` was 0, no telemetry events were sent.

**Comment by maxxcrawford** [comment] 2019-09-26 19:59
Ran testing with the following method and got these results: 

|Test|Result|
|-|-|
|Test 1: Default|Passed|
|Test 2: Policy Disabled|Passed|
|Test 3: Policy Removed|Passed|
|Test 4: Policy Enabled|Passed|
|Test 5: Policy Disabled (Recheck) |Passed|

### Setup
- New profile
- Add/set the following prefs:
  - `doh-rollout.enabled` : `true`
  - `xpinstall.signatures.require` : `true`
  - `xpinstall.signatures.dev-root` : `true`
- **No** policy added
- Install signed XPI 

### Test 1: Default (On)
- Click doorhanger button: "OK" 

Expected Results: 
- Doorhanger to show, `network.trr.mode` : `2`, telemetry events (Doh_Enabled, UIok) 

### Test 1: Policy Disabled
- Quit application completely 
- Added policies.json, `DNSoverHTTPS` set to `false`
- Open Firefox
- In `about:config`, `network.trr.mode` : `0`, telemetry events (DoH_Disabled, UIState Disabled) 

### Test 3: Policy Removed
- Quit application completely 
- Remove policies file 
- Open Firefox
- In `about:config`, `network.trr.mode` : `2`, telemetry events (Doh_Enabled, UIok) 

### Test 4: Policy Enabled
- Quit application completely 
- Added policies.json, `DNSoverHTTPS` set to `true`
- Open Firefox
- In `about:config`, `network.trr.mode` : `2`, telemetry events (Doh_Enabled, UIok)

### Test 5: Policy Disabled (Recheck)
- Quit application completely 
- Added policies.json, `DNSoverHTTPS` set to `false`
- Open Firefox
- In `about:config`, `network.trr.mode` : `0`, telemetry events (DoH_Disabled, UIState Disabled) 

Sample "Disabled" policies file: 
- [policies.json.txt](https://github.com/mozilla/doh-rollout/files/3659659/policies.json.txt)

**Comment by maxxcrawford** [comment] 2019-09-27 23:46
Please verify with https://github.com/mozilla/doh-rollout/releases/tag/0.0.9rc1

**Comment by SoftVision-CarmenFat** [comment] 2019-09-30 12:47
- Tested this scenario with the latest version of the add-on 0.0.9rc1 and the issue is still reproducible accross channels (Release 69, Beta 70 and Nightly 71).
- There is no telemetry event displayed after restarting the browser.

**Comment by maxxcrawford** [comment] 2019-10-02 21:08
Re-opening for @Softvision-PatriciuPop to verify.

**Comment by SoftVision-CarmenFat** [comment] 2019-10-03 11:37
- Tested this using the latest version of the add-on 0.0.10 and the issue is still reproducible on our side.
- There is no telemetry event displayed after restarting the browser, nor after updating the "disable" policy to a "enable" one.

**Comment by maxxcrawford** [comment] 2019-10-03 14:49
@SoftVision-CarmenFat Can we schedule a video call to walk through this issue together? I want to make sure I'm understand the test process, as I cannot reproduce it on my side. Thanks!

**Comment by maxxcrawford** [comment] 2019-10-03 22:27
@SoftVision-CarmenFat @Softvision-PatriciuPop Please use the latest release - https://github.com/mozilla/doh-rollout/releases/tag/0.0.11. Note that this build is signed for full release, so do not use the pref, `xpinstall.signatures.dev-root!

**Comment by SoftVision-CarmenFat** [comment] 2019-10-04 13:17
@maxxcrawford
I investigated this issue a bit further and found 2 scenarios that have 2 different results (and might be a reason why it's fixed on your side, but on ours still seems reproducible).

Case 1:
1. Add the "distribution" folder to the "core" folder from the Firefox installation folder.
2. Add the disable "DNSOverHTTPS" policy to the "distribution" folder.
3. Create and open a new Firefox profile.
4. Install the 0.0.11 add-on and set the "doh-rollout.enabled" preference to "true".
5. Restart the browser and check the "about:telemetry" page.

Actual result: There is no telemetry event displayed.


Case 2:
1. Create and open a new Firefox profile.
2. Install the 0.0.11 add-on and set the "doh-rollout.enabled" preference to "true".
3. Click the "Ok, got it" from the doorhanger.
4. Go to the "core" folder from the Firefox installation folder and add the "distribution" folder.
5. Add the disable "DNSOverHTTPS" policy to the "distribution" folder.
6. Restart the browser and check the "about:telemetry" page.

Actual result: the "startup" event is displayed.

Maxx, is this helpful for you in any way?

**Comment by maxxcrawford** [comment] 2019-10-07 23:46
@Softvision-PatriciuPop @SoftVision-CarmenFat Tested both edge cases with v0.0.12 – Please verify! https://github.com/mozilla/doh-rollout/releases/tag/0.0.12

**Comment by SoftVision-CarmenFat** [comment] 2019-10-08 12:47
- Tested both cases from the previous [comment ](https://github.com/mozilla/doh-rollout/issues/94#issuecomment-538392874)using the latest 0.0.12 version of the add-on and the issue is no longer reproducible. 
- The "disable_doh" telemetry event is now generated after restarting the browser. 
- Also, the "enable_doh" telemetry event is generated after changing the "disable" "DNSOverHTTPS" policy to an "enable" one.
- Tested on Window s10 x64 across channels : Release 69.0.2, Beta 70.0b12 and latest Nightly 71.0a1.

**Closed** 2019-10-09 15:34 UTC
Labels: P1
