### ISSUE TITLE
The DoH doorhanger is not displayed again after reopening the tab on which it was previously triggered

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#180] opened 2019-11-11 16:34 UTC
**[Affected Platforms]:**
- All Windows

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
 
**[Prerequisites]:**
- Have an active Normandy testing recipe for DoH.
- You are enrolled in the Treatment branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Close the tab where the DoH doorhanger is displayed.
3. Reopen the previosuly closed tab and observe the behavior.

**[Expected result]:**
- The tab is reopened and the DoH doorhanger is displayed again.

**[Actual result]:**
- The tab is reopened but the DoH doorhanger is no longer displayed.

**[Notes]:**
- According to this [comment](https://github.com/mozilla/doh-rollout/issues/136#issuecomment-540054160), the doorhanger should continue to be triggered unless the user does any of the following actions:
	- Clicks okay
	- Clicks disable protections
	- Clicks "esc" key while its in focus (triggers an okay click)
- The issue is reproducible with the 1.1.0rc1 version of the add-on.
- I have attached a screen recording of the issue:

![doorhanger](https://user-images.githubusercontent.com/26000308/68603478-fe92a500-04b0-11ea-8fd4-95f5e3d1aea0.gif)

**Comment by maxxcrawford** [comment] 2019-11-11 16:36
Once the doorhanger is removed from the current context (Tab close is an example of this), it won't show again until network change or browser restart. 

This is expected behavior, I believe. 

@nhi-nguyen Thoughts?

**Comment by SoftVision-CarmenFat** [comment] 2019-11-11 16:39
Actually, on browser restart, the doorhanger is displayed again. This only happens when reopening the tab.

**Comment by mythmon** [comment] 2019-11-11 18:45
Since the tab isn't (logically) associated with that particular tab, it seems that it shouldn't be affected by that tab closing. I realize that in the code the doorhanger is related to a particular tab, but that isn't something that is consistent with the message we are trying to send, since the message is about the browser, not a tab.

**Comment by nhi-nguyen** [comment] 2019-11-12 01:16
Agree that the doorhanger isn't associated with a particular tab, and its behaviour should reflect that. However, this is the way it is currently implemented, and the reported behaviour is consistent with how it currently works.

This is an issue, but not a blocking one for this release. It will be done for https://github.com/mozilla/doh-rollout/issues/158, which will be in v1.3.

**Comment by maxxcrawford** [comment] 2019-12-19 05:36
Bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605009

**Closed by maxxcrawford** 2019-12-19 05:36 UTC
